# Numpy biblioteka #

NumPy je jedna od najvaznijih biblioteka za Python. Glavna svrha je rad s visedimenzionalnim poljima (nizovima) i matricama.

In [1]:
import numpy as np

In [14]:
# numpy niz
niz = np.array([1,6,0]) # kreiranje niza od zadatih elemenata
print(niz)
print(niz.shape) # vraca oblik niza, (3,) - nedostatak drugog indeksa oznacava da je u pitanju niz
# numpy niz nije torka ili lista, to je novi tip
print(type(niz))

[1 6 0]
(3,)
<class 'numpy.ndarray'>


In [19]:
# indeksiranje se radi na isti nacin kao sa lista
print(f"prvi clan : {niz[0]}, drugi clan: {niz[1]}, treci clan {niz[2]}")
print(f"duzina niza je {len(niz)}")

prvi clan : 1, drugi clan: 6, treci clan 0
duzina niza je 3


In [21]:
# takodje, ovi nizovi su promenjiog tipa, sto znaci da mozemo menjati elemente unutar niza
niz[2] = 10
print(niz)

[ 1  6 10]


In [28]:
# visedimenzionalni niz
niz2 = np.array([[1,2, 3], [4,5,7], [6,7,9], [0,6,2]])
print(niz2)
print(niz2.shape) # 4x3 4 vrste i 3 kolone
# indeksiranje elemenata dvodimenzionalnog niza
print(f"niz2[0][2] = {niz2[0][2]}") # prvi nacin
print(f"niz2[0, 2] = {niz2[0, 2]}") # drugi nacin

[[1 2 3]
 [4 5 7]
 [6 7 9]
 [0 6 2]]
(4, 3)
niz2[0][2] = 3
niz2[0, 2] = 3


In [49]:
# inicijalizacija nekih posebnih nizova

# matrica oblika 3x2 koja ima sve nule
a = np.zeros((3,2))
print(a)

# matrica oblika 2x3 koja ima sve jedinice
b = np.ones((2,3))
print(b)

# matrica oblika 3x3 ciji su svi elementi jednaki broju 5
c = np.full((3,3), 5)
print(c)

# jedinicna matrica oblika 3x3
d = np.eye(3)
print(d)

# random matrica
# ako zelimo da svaki put dobijemo iste brojeve, onda mozemo postaviti neki seed,
# to je korisni radi testiranja, debagovanja....
np.random.seed(10)
e = np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]


In [63]:
# izdvajanje podniza
A = np.array([[1,2,3,4],[5,6,7,8],[8,9,10,11]])
print(A)
# biramo sve vrste ciji je indeks manji od 2 i kolone sa indeksom vecim ili jednakim 1, a manjim od 3
B = A[:2, 1:3]
print(B)

# vazno napomenuti
# ovde B nije bova matrica, ona je samo pogled na matricu A
# dakle, ako menjamo elemente jedne matrice, promene se i elementi u drugoj matrici

B[1,0] = 100
print(B)
print(A)

# ako zelimo novu matricu, potrebno je koristit copy
C = A[:2, 1:3].copy()
A[0,2] = 300
print(A) # promenjeno
print(B) # promenjeno
print(C) # nije se promenilo

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 8  9 10 11]]
[[2 3]
 [6 7]]
[[  2   3]
 [100   7]]
[[  1   2   3   4]
 [  5 100   7   8]
 [  8   9  10  11]]
[[  1   2 300   4]
 [  5 100   7   8]
 [  8   9  10  11]]
[[  2 300]
 [100   7]]
[[  2   3]
 [100   7]]


In [82]:
# razne operacije sa nizovima

# mozemo da ih sabiramo po koordinatama
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(f" x + y =\n {x+y}\n")

# oduzimanje po koordinatama
print(f" x - y =\n {x-y}\n")

# mnozenje po koordinatama
print(f" x * y =\n {x*y}\n")

# deljenje po koordinatama
print(f" x / y =\n {x/y}\n")

# kvadriranje svakog elementa
print(f" x**2 = \n {x**2}\n")

 x + y =
 [[ 6  8]
 [10 12]]

 x - y =
 [[-4 -4]
 [-4 -4]]

 x * y =
 [[ 5 12]
 [21 32]]

 x / y =
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]

 x**2 = 
 [[ 1  4]
 [ 9 16]]



In [88]:
# Ukoliko zelimo matricno mnozenje , koristimo dot

print(f" x.dot(y) =\n {x.dot(y)}\n")

# dot moze da se koristi i za skalarni prozivod dva vektora
v = np.array([1,2,3])
u = np.array([5,6,7])

print(f" u.dot(v) =\n {u.dot(v)}\n")

 x.dot(y) =
 [[19 22]
 [43 50]]

 u.dot(v) =
 38



In [95]:
# jos neke korisne mogucnosti numpy biblioteke

X = np.array([[1,2,4], [-10,6,3], [7,1,0], [12,3 ,-2]])
print(X)

# numpy.sum() - racuna zbor svih vrednosti u nizu.
print(f"Zbir svih elemenata matrice X je {np.sum(X)}")

# numpy.mean() - racuna aritmeticku sredinu svih vrednosti u nizu.
print(f"Aritmeticka sredina elemenata matrice X je {np.mean(X)}")

# numpy.max() - vraca najvecu vrijednost u nizu.
print(f"Najveci element matrice X je {np.max(X)}")

# numpy.min() - vraca najmanju vrednost u nizu.
print(f"Najmanji element matrice X je {np.min(X)}")

[[  1   2   4]
 [-10   6   3]
 [  7   1   0]
 [ 12   3  -2]]
Zbir svih elemenata matrice X je 27
Aritmeticka sredina elemenata matrice X je 2.25
Najveci element matrice X je 12
Najmanji element matrice X je -10


In [120]:
# numpy.arange()
# stvara niz s vrednostima koje su jednako razmaknute. 
# Argumenti su pocetna vrednost, krajnja vrednost i korak.
m = np.arange(1, 20, 2)
print(m)

# numpy.linspace() 
# stvara niz s vrednostima koje su jednako razmaknute. 
# Argumenti su pocetna vrednost, krajnja vrednost i broj tacaka u nizu.
n = np.linspace(1, 20, 10)
print(n)

# numpy.reshape() - menja oblik polja.
m1 = m.reshape(2,5)
print(m1)

# numpy.concatenate() - spaja dva ili više nizova u jedan.
print(np.concatenate((m,n)))

# mozemo da radimo i konkatenaciju matrica
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

# Spajamo matrice po dimenziji 0
C = np.concatenate([A, B], axis=0)
print(C)

# Spajamo matrice po dimenziji 1
D = np.concatenate([A, B], axis=1)
print(D)

[ 1  3  5  7  9 11 13 15 17 19]
[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]
[[ 1  3  5  7  9]
 [11 13 15 17 19]]
[ 1.          3.          5.          7.          9.         11.
 13.         15.         17.         19.          1.          3.11111111
  5.22222222  7.33333333  9.44444444 11.55555556 13.66666667 15.77777778
 17.88888889 20.        ]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Numpy.linalg modul ##
Modul *numpy.linalg* pruža funkcionalnost linearne algebre u NumPy-u. U nastavku su navedene neke od najvaznijih funkcija ovog modula:

    numpy.linalg.inv: Izracunava inverz matrice.
    numpy.linalg.det: Izracunava determinantu matrice.
    numpy.linalg.eig: Izracunava sopstvene vektore i sopstvene vrednosti matrice.
    numpy.linalg.solve: Resava linearni sistem jednadžbi Ax = b za x.
    numpy.linalg.norm: Izracunava normu vektora ili matrice.

In [121]:
import numpy.linalg as LA

In [139]:
A = np.array([[1,2],[8,5]])
print(A)

[[1 2]
 [8 5]]


In [142]:
# determinanta matrice A
print(LA.det(A))

# inverz
A_inv = LA.inv(A)
print(A_inv)

print(A.dot(A_inv))


-10.999999999999996
[[-0.45454545  0.18181818]
 [ 0.72727273 -0.09090909]]
[[1. 0.]
 [0. 1.]]


In [152]:
# sopstvene vrednosti i vektori
[sVrednosti, sVektori] = LA.eig(A)
# prva kolona u sVektori je prvi sopstveni vektor, a druga drugi
# provera da li je rezultat dobar 
print(f"{A.dot(sVektori[:,0])} == {sVrednosti[0]*sVektori[:,0]}")
print(f"{A.dot(sVektori[:,1])} == {sVrednosti[1]*sVektori[:,1]}")

[ 0.92591488 -1.14449373] == [ 0.92591488 -1.14449373]
[-2.20608694 -7.13904729] == [-2.20608694 -7.13904729]


In [154]:
# resi jednacine 2x + 3y = 13, 5x - y = 7
[x,y] = LA.solve(np.array([[2,3],[5,-1]]), np.array([13,7]))
print(f"resenje je x = {x}, y = {y}")

resenje je x = 2.0, y = 3.0


In [155]:
# racunanje norme matrice
LA.norm(A)

9.695359714832659